# Generated by Django 4.2.2 on 2023-06-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_options_alter_new_photo_alter_new_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
    ]
